addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.21.0")
addSbtPlugin("io.github.sbt-doctest" % "sbt-doctest" % "0.12.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.8.5")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.8.5")
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.5.11")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
