addSbtPlugin("com.eed3si9n"        % "sbt-unidoc"               % "0.4.3")
addSbtPlugin("org.scala-js"        % "sbt-scalajs"              % "1.1.0")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest"              % "0.9.6")
addSbtPlugin("com.47deg"           % "sbt-microsites"           % "1.2.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"             % "2.4.0")
addSbtPlugin("org.portable-scala"  % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("com.codecommit"      % "sbt-spiewak-sonatype"     % "0.14-7c437d7")
